// <auto-generated />
namespace FitnesSkopjeWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class gym_types : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gym_types));
        
        string IMigrationMetadata.Id
        {
            get { return "202112171901395_gym_types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
