// <auto-generated />
namespace FitnesSkopjeWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fav_GymName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fav_GymName));
        
        string IMigrationMetadata.Id
        {
            get { return "202112061902275_Fav_GymName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
